# Generated by Django 3.2.5 on 2021-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='')),
                ('transcript', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
